version: '3.8'

services:
  # Backend API Service
  backend-dev:
    build: 
      context: .
      target: development
    container_name: backend-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/backend/src
      - ./package.json:/backend/package.json
      - ./tsconfig.json:/backend/tsconfig.json
      - ./prisma:/backend/prisma
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@postgres:5432/liveupclip_backend_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npx prisma generate && npm run dev"

  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: liveupclip_backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d liveupclip_backend_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge 